-- Generated by generate-art.py -- do not edit.
-- Expects the caller to set the global `os99_dir` to this directory.
local D = os99_dir

-- Compositor-level settings; no plugin required, so kept in their own pcall.
pcall(function()
  hl.config({
    general = { border_size = 0 },
    misc = { background_color = "rgb(54679B)" },
    group = { groupbar = { font_family = "Charcoal", font_size = 12 } },
    decoration = {
      shadow = { enabled = true, sharp = true, range = 0, render_power = 1,
                 offset = { 2, 3 },
                 color = "rgba(00000099)", color_inactive = "rgba(00000038)" },
    },
  })
end)

-- The plugin's own keys. These only exist once hyprbars is loaded, and on a
-- cold start the config is parsed before that -- hence the pcall, so an unknown
-- key cannot take the rest of the user's config down with it.
pcall(function()
  hl.config({ plugin = { hyprbars = {
    bar_height = 28,
    bar_color = "rgb(D5D6D5)",
    bar_texture = D .. "/bar",
    bar_texture_border = "0 3 0 3",
    frame_texture = D .. "/frame",
    frame_texture_border = "35 8 8 8",
    frame_inset = "28 6 6 6",
    frame_texture_unscaled = true,
    frame_over_window = true,
    bar_clear_color = "rgb(D5D6D5)",
    bar_text_clear_pad = 8,
    bar_button_clear_pad = 7,
    bar_clear_inset_top = 2,
    bar_clear_inset_bottom = 1,
    bar_text_font = "Charcoal",
    bar_text_size = 12,
    bar_text_align = "center",
    bar_part_of_window = true,
    bar_precedence_over_border = true,
    bar_buttons_alignment = "left",
    bar_padding = 1,
    bar_button_padding = 4,
    col = { text = "rgb(000000)" },
  } } })
end)

-- The boxes. hyprbars clears its button list on every config reload and never
-- repopulates ones added through the Lua API, so they have to be redeclared
-- here or every reload empties the title bar. clear_buttons (a fork addition)
-- makes it idempotent. Close alone on the LEFT, collapse and zoom on the RIGHT;
-- buttons fill outward from their own edge, so zoom goes first to keep the
-- top-right corner it has held since System 7.
pcall(function()
  hl.plugin.hyprbars.clear_buttons()
  local box = { bg_color = "rgb(D5D6D5)", fg_color = "rgb(000000)", size = 14, icon = "" }
  local function add(img, side, dispatch)
    hl.plugin.hyprbars.add_button({ bg_color = box.bg_color, fg_color = box.fg_color,
      size = box.size, icon = "", image = D .. img, side = side, dispatch = dispatch })
  end
  -- `dispatch` runs the action IN THE PLUGIN, against this window. The shell
  -- form (`action = "hyprctl dispatch ..."`) still works but has two problems:
  -- it acts on whatever window is ACTIVE rather than the one you clicked, and
  -- it cannot ask for a maximise that keeps the decorations -- Hyprland's Lua
  -- fullscreen binding ignores its mode argument and always goes true
  -- fullscreen, which hides the very title bar you would click to undo it.
  add("/bar_close.png",    "left",  "close")
  add("/bar_zoom.png",     "right", "maximize")
  add("/bar_collapse.png", "right", "float")
end)
