-- Generated by generate-art.py -- do not edit.
-- Expects the caller to set the global `os99_dir` to this directory.
local D = os99_dir

-- Is the plugin actually loaded? Everything that makes this theme look like a
-- window frame comes from it, so when it is absent -- not installed yet, or
-- disabled via the os99-no-bars kill switch -- the compositor settings that
-- only make sense ALONGSIDE a frame must not be applied. Turning the border off
-- with no frame to replace it leaves windows with no edge at all.
local have_plugin = false
pcall(function() have_plugin = hl.plugin ~= nil and hl.plugin.hyprbars ~= nil end)

-- Compositor-level settings; no plugin required, so kept in their own pcall.
pcall(function()
  hl.config({
    general = { border_size = have_plugin and 0 or 1 },
    misc = { background_color = "rgb(54679B)" },
    group = { groupbar = { font_family = "Charcoal", font_size = 12 } },
    decoration = {
      shadow = { enabled = true, sharp = true, range = 0, render_power = 1,
                 offset = { 2, 3 },
                 color = "rgba(00000099)", color_inactive = "rgba(00000038)" },
    },
  })
end)

-- The plugin's own keys. These exist only once hyprbars is loaded.
--
-- GUARDED, not merely pcall'd. hl.config RECORDS an unknown key as a config
-- error before it raises, so a pcall catches the exception but still leaves
-- "unknown config key 'plugin.hyprbars.*'" on Hyprland's error overlay -- once
-- per key. On a cold start the config is parsed before the plugin loads, and
-- with the kill switch set it never loads at all, so that overlay would be
-- permanent. Skipping the block entirely is the only way to stay quiet.
--
-- Nothing is lost by skipping: os99-window-bars re-runs this same file through
-- `hyprctl eval` once the plugin IS loaded, and on a reload with the plugin
-- already up have_plugin is true and these apply immediately.
if have_plugin then
  hl.config({ plugin = { hyprbars = {
    bar_height = 28,
    bar_color = "rgb(5F5F5F)",
    bar_texture = D .. "/bar",
    bar_texture_border = "0 3 0 3",
    frame_texture = D .. "/frame",
    frame_texture_border = "28 6 6 6",
    frame_inset = "28 6 6 6",
    frame_texture_unscaled = false,
    frame_over_window = true,
    bar_clear_color = "rgb(5F5F5F)",
    bar_text_clear_pad = 8,
    bar_button_clear_pad = 7,
    bar_clear_inset_top = 2,
    bar_clear_inset_bottom = 1,
    bar_text_font = "Charcoal",
    bar_text_size = 12,
    bar_text_align = "center",
    bar_part_of_window = true,
    bar_precedence_over_border = true,
    bar_buttons_alignment = "left",
    bar_padding = 1,
    bar_button_padding = 4,
    col = { text = "rgb(F0F0F0)" },
  } } })
end

-- The boxes. hyprbars clears its button list on every config reload and never
-- repopulates ones added through the Lua API, so they have to be redeclared
-- here or every reload empties the title bar. clear_buttons (a fork addition)
-- makes it idempotent. Close alone on the LEFT, collapse and zoom on the RIGHT;
-- buttons fill outward from their own edge, so zoom goes first to keep the
-- top-right corner it has held since System 7.
if have_plugin then
  hl.plugin.hyprbars.clear_buttons()
  local box = { bg_color = "rgb(5F5F5F)", fg_color = "rgb(F0F0F0)", size = 12, icon = "" }
  local function add(img, side, dispatch)
    hl.plugin.hyprbars.add_button({ bg_color = box.bg_color, fg_color = box.fg_color,
      size = box.size, icon = "", image = D .. img, side = side, dispatch = dispatch })
  end
  -- `dispatch` runs the action IN THE PLUGIN, against this window. The shell
  -- form (`action = "hyprctl dispatch ..."`) still works but has two problems:
  -- it acts on whatever window is ACTIVE rather than the one you clicked, and
  -- it cannot ask for a maximise that keeps the decorations -- Hyprland's Lua
  -- fullscreen binding ignores its mode argument and always goes true
  -- fullscreen, which hides the very title bar you would click to undo it.
  add("/bar_close.png",    "left",  "close")
  add("/bar_zoom.png",     "right", "maximize")
  add("/bar_collapse.png", "right", "float")
end
